# Generated by Django 3.1.2 on 2022-01-30 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20220130_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scopes', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='tagsarticle',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scopes', to='articles.tags'),
        ),
    ]
