# Generated by Django 3.1.2 on 2022-01-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20220130_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagsarticle',
            old_name='tags',
            new_name='tag',
        ),
    ]
