# Generated by Django 3.1.2 on 2022-01-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20220130_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagsarticle',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
