# Generated by Django 3.1.2 on 2022-01-30 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_tagsarticle_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tagsarticle',
            options={'ordering': ['is_main']},
        ),
    ]
