# Generated by Django 3.1.2 on 2022-01-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20220130_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagsarticle',
            options={'ordering': None},
        ),
    ]
